-- MySQL Script generated by MySQL Workbench
-- Thu Aug 11 21:46:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE `mydb`;
-- -----------------------------------------------------
-- Table `mydb`.`income_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`income_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`income`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`income` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10, 2) NOT NULL,
  `date_of_operation` DATETIME NOT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_income_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_income_categories1` FOREIGN KEY (`categories_id`) REFERENCES `mydb`.`income_categories` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`costs_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`costs_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`costs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`costs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10, 2) NOT NULL,
  `date_of_operation` DATETIME NOT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_costs_costs_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_costs_costs_categories1` FOREIGN KEY (`categories_id`) REFERENCES `mydb`.`costs_categories` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

INSERT INTO costs_categories(category)
VALUES("Транспорт"),
  ("Продукты"),
  ("Развлечения"),
  ("Одежда"),
  ("Здоровье и красота"),
  ("Электроника"),
  ("Коммунальные платежи");

INSERT INTO  income_categories(category)
VALUES("Зарплата"),
  ("Перевод");
